package formulario;

import clases.Metodo_Ordenamiento;
import clases.Metodo_busqueda;
import productos.productosAbarrote;

import java.util.ArrayList;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author maria
 */
public class Bodega extends javax.swing.JFrame {

    Metodo_Ordenamiento metodos_Ordenamiento = new Metodo_Ordenamiento();
    Metodo_busqueda metodos_busqueda = new Metodo_busqueda();

    String[] columnas = {"Código", "Nombre", "Cantidad", "Precio", "Descripción", "Proveedor"};
    DefaultTableModel model = new DefaultTableModel(columnas, 0);

    productosAbarrote pAbarrotes = new productosAbarrote();
    Object[][] listaProductos = pAbarrotes.productosAbarrotes;

    public Bodega() {
        initComponents();
        this.setLocationRelativeTo(null);


        //<editor-fold defaultstate="collapsed" desc="Tabla">
        tablaDatos.setRowHeight(28);
        productosAbarrote pAbarrotes = new productosAbarrote();

        // Agregar filas
        Object[][] listaProductos = pAbarrotes.productosAbarrotes;
        for (Object[] fila : listaProductos) {
            model.addRow(fila);
        }
        // Asignar modelo a la tabla
        tablaDatos.setModel(model);
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Botones">

        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelBusqueda = new javax.swing.JPanel();
        infoCodigo = new javax.swing.JLabel();
        infoNombre = new javax.swing.JLabel();
        infoStock = new javax.swing.JLabel();
        infoPrecio = new javax.swing.JLabel();
        infoProveedor = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelSearch = new javax.swing.JPanel();
        infoSearch = new javax.swing.JLabel();
        listProv = new javax.swing.JComboBox<>();
        panelOrdenamiento = new javax.swing.JPanel();
        infoOrdenamiento = new javax.swing.JPanel();
        infoOrden = new javax.swing.JLabel();
        radioCodigo = new javax.swing.JRadioButton();
        radioNombre = new javax.swing.JRadioButton();
        radioStock = new javax.swing.JRadioButton();
        radioPrecio = new javax.swing.JRadioButton();
        radioProovedor = new javax.swing.JRadioButton();
        scrollPanelTabla = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoutp.jpeg"))); // NOI18N
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        panelHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 290, 80));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        panelHeader.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 50, 60));

        jLabel4.setText("Administrador in Retail");
        panelHeader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, -1, -1));

        jPanel2.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1130, 80));

        panelBusqueda.setBackground(new java.awt.Color(231, 231, 231));
        panelBusqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoCodigo.setText("Codigo :");
        panelBusqueda.add(infoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 55, -1, -1));

        infoNombre.setText("Nombre :");
        panelBusqueda.add(infoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        infoStock.setText("Stock :");
        panelBusqueda.add(infoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        infoPrecio.setText("Precio :");
        panelBusqueda.add(infoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        infoProveedor.setText("Proveedor:");
        panelBusqueda.add(infoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        panelBusqueda.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 52, 163, -1));
        panelBusqueda.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 80, 163, -1));
        panelBusqueda.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 108, 163, -1));
        panelBusqueda.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 136, 163, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 0, 0));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        panelSearch.setBackground(new java.awt.Color(218, 218, 218));
        panelSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        infoSearch.setText("Búsqueda");

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(infoSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBusqueda.add(panelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 301, -1));

        listProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "San Fernando", "Gloria", "Cafetalero San Juan", "Corporación Lindley" }));
        listProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listProvActionPerformed(evt);
            }
        });
        panelBusqueda.add(listProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, -1));

        jPanel2.add(panelBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 250));

        panelOrdenamiento.setBackground(new java.awt.Color(211, 211, 211));
        panelOrdenamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelOrdenamiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoOrdenamiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        infoOrden.setText("Ordenamiento");

        javax.swing.GroupLayout infoOrdenamientoLayout = new javax.swing.GroupLayout(infoOrdenamiento);
        infoOrdenamiento.setLayout(infoOrdenamientoLayout);
        infoOrdenamientoLayout.setHorizontalGroup(
            infoOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoOrdenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoOrden)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoOrdenamientoLayout.setVerticalGroup(
            infoOrdenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoOrdenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoOrden)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOrdenamiento.add(infoOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        radioCodigo.setText("Codigo");
        radioCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCodigoActionPerformed(evt);
            }
        });
        panelOrdenamiento.add(radioCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        radioNombre.setText("Nombre");
        radioNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNombreActionPerformed(evt);
            }
        });
        panelOrdenamiento.add(radioNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        radioStock.setText("Stock");
        radioStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioStockActionPerformed(evt);
            }
        });
        panelOrdenamiento.add(radioStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        radioPrecio.setText("Precio");
        radioPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPrecioActionPerformed(evt);
            }
        });
        panelOrdenamiento.add(radioPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        radioProovedor.setText("Proveedor");
        radioProovedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioProovedorActionPerformed(evt);
            }
        });
        panelOrdenamiento.add(radioProovedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jPanel2.add(panelOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 300, 110));

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Stock", "Precio", "Descripcion", "Proveedor"
            }
        ));
        scrollPanelTabla.setViewportView(tablaDatos);

        jPanel2.add(scrollPanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 784, 370));

        btnRefrescar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefrescarMouseClicked(evt);
            }
        });
        jPanel2.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 40, 40));

        jLabel5.setText("- Mantenimiento / Productos");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            String codigoBuscado = txtCodigo.getText();
            ArrayList<String> productoEncontrado = metodos_busqueda.buscarProductoPorCodigo(codigoBuscado, listaProductos);
            this.busquedaUno(productoEncontrado);
        }

        if (!txtNombre.getText().isEmpty()) {
            String nombreBuscado = txtNombre.getText();
            ArrayList<String[]> productoEncontrado = metodos_busqueda.buscarProductoPorNombre2(nombreBuscado, listaProductos);
            this.buscarDos(productoEncontrado);
            String mensaje = "Producto No Encontrado";
            this.validarVacio(productoEncontrado,mensaje);
        }

        if (!txtPrecio.getText().isEmpty()) {
            String precioBuscado = txtPrecio.getText();
            double precio = Double.parseDouble(precioBuscado);
            ArrayList<String[]> productoEncontrado = metodos_busqueda.buscarProductoPorPrecio2(precio, listaProductos);
            this.buscarDos(productoEncontrado);
            String mensaje = "Precio No Encontrado";
            this.validarVacio(productoEncontrado,mensaje);

        }

        if (!txtStock.getText().isEmpty()) {
            String stockBuscado = txtStock.getText();
            int stock = Integer.parseInt(stockBuscado);
            ArrayList<String[]> productoEncontrado = metodos_busqueda.buscarProductoPorStock2(stock, listaProductos);
            this.buscarDos(productoEncontrado);
            String mensaje = "Stock No Encontrado";
            this.validarVacio(productoEncontrado,mensaje);

        }

        if (!listProv.getSelectedItem().equals("Seleccionar")) {
            String proovedorBuscado = (String) listProv.getSelectedItem();
            ArrayList<String[]> productoEncontrado = metodos_busqueda.buscarProductoPorProovedor2(proovedorBuscado, listaProductos);
            this.buscarDos(productoEncontrado);
            String mensaje = "Proveedor No Encontrado";
            this.validarVacio(productoEncontrado,mensaje);

        }

        if (!listProv.getSelectedItem().equals("Seleccionar") && !txtNombre.getText().isEmpty()) {
            String nombreBuscado = txtNombre.getText();
            String proovedorBuscado = (String) listProv.getSelectedItem();
            ArrayList<String[]> productoEncontrado = metodos_busqueda.buscarProductoPorNombreYProveedor(nombreBuscado, proovedorBuscado, listaProductos);
            this.buscarDos(productoEncontrado);
            String mensaje = "Proveedor & Nombre No Encontrado";
            this.validarVacio(productoEncontrado,mensaje);

        }

        if (!txtPrecio.getText().isEmpty() && !txtStock.getText().isEmpty()) {
            String precioBuscado = txtPrecio.getText();
            double precio = Double.parseDouble(precioBuscado);

            String stockBuscado = txtStock.getText();
            int stock = Integer.parseInt(stockBuscado);

            ArrayList<String[]> productoEncontrado = metodos_busqueda.buscarProductoPorStockYPrecio(stock, precio, listaProductos);
            String mensaje = "Precio & Stock No Encontrado";
            this.buscarDos(productoEncontrado);
            this.validarVacio(productoEncontrado,mensaje);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefrescarMouseClicked
     model.setRowCount(0);
        for (Object[] fila : pAbarrotes.productosRes) {
            model.addRow(fila);
        }
        tablaDatos.setModel(model);        
        this.limpiar();
        this.radioCodigo.setSelected(false);
        this.radioNombre.setSelected(false);
        this.radioPrecio.setSelected(false);
        this.radioProovedor.setSelected(false);
        this.radioStock.setSelected(false);

    }//GEN-LAST:event_btnRefrescarMouseClicked

    private void listProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProvActionPerformed
    }//GEN-LAST:event_listProvActionPerformed

    private void radioCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCodigoActionPerformed
        this.botonesOrdenar();
    }//GEN-LAST:event_radioCodigoActionPerformed

    private void radioNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNombreActionPerformed
        this.botonesOrdenar();
    }//GEN-LAST:event_radioNombreActionPerformed

    private void radioStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioStockActionPerformed
        this.botonesOrdenar();
    }//GEN-LAST:event_radioStockActionPerformed

    private void radioPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPrecioActionPerformed
        this.botonesOrdenar();
    }//GEN-LAST:event_radioPrecioActionPerformed

    private void radioProovedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioProovedorActionPerformed
        this.botonesOrdenar();
    }//GEN-LAST:event_radioProovedorActionPerformed

    public void botonesOrdenar(){
        
        if(radioCodigo.isSelected()){
        metodos_Ordenamiento.ordenarCodigo(pAbarrotes.productosAbarrotes);
        this.mostrarTabla();        
        }
        
        if(radioNombre.isSelected()){
        metodos_Ordenamiento.ordenarNombre(pAbarrotes.productosAbarrotes);
        this.mostrarTabla();        
        }
        
        if(radioStock.isSelected()){
        metodos_Ordenamiento.ordenarStock(pAbarrotes.productosAbarrotes);
        this.mostrarTabla();        
        }
        
        if(radioPrecio.isSelected()){
        metodos_Ordenamiento.ordenarPrecio(pAbarrotes.productosAbarrotes);
        this.mostrarTabla();        
        }
        
        if(radioProovedor.isSelected()){
        metodos_Ordenamiento.ordenarProveedor(pAbarrotes.productosAbarrotes);
        this.mostrarTabla();        
        }
        
        if(radioPrecio.isSelected() && radioStock.isSelected()){
        metodos_Ordenamiento.ordenarPorSeleccion(pAbarrotes.productosAbarrotes);
        this.mostrarTabla();        
        }
    }
    
    public void validarVacio(ArrayList<String[]> productoEncontrado , String mensaje ) {
        if(productoEncontrado.isEmpty()){
            JOptionPane.showMessageDialog(null, mensaje);        }
    }
    
    public void limpiar() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        listProv.setSelectedItem(listProv.getItemAt(0));
        txtStock.setText("");
    }

    public void buscarDos(ArrayList<String[]> productoEncontrado) {
        String[] columnas = {"Código", "Nombre", "Cantidad", "Precio", "Descripción", "Proveedor"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        for (String[] fila : productoEncontrado) {
            modelo.addRow(fila);
        }

        tablaDatos.setModel(modelo);
    }

    public void mostrarTabla() {
        model.setRowCount(0);
        for (Object[] fila : pAbarrotes.productosAbarrotes) {
            model.addRow(fila);
        }
        tablaDatos.setModel(model);
    }

    public void busquedaUno(ArrayList<String> detallesProducto) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Código");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Cantidad");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Descripción");
        modeloTabla.addColumn("Proveedor");

        if (!detallesProducto.get(0).equals("Producto no encontrado.")) {
            Object[] fila = new Object[6];
            for (int i = 0; i < detallesProducto.size(); i++) {
                fila[i] = detallesProducto.get(i).split(": ")[1];
            }
            modeloTabla.addRow(fila);
        }
        tablaDatos.setModel(modeloTabla);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bodega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel btnRefrescar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel infoCodigo;
    private javax.swing.JLabel infoNombre;
    private javax.swing.JLabel infoOrden;
    private javax.swing.JPanel infoOrdenamiento;
    private javax.swing.JLabel infoPrecio;
    private javax.swing.JLabel infoProveedor;
    private javax.swing.JLabel infoSearch;
    private javax.swing.JLabel infoStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> listProv;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelOrdenamiento;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JRadioButton radioCodigo;
    private javax.swing.JRadioButton radioNombre;
    private javax.swing.JRadioButton radioPrecio;
    private javax.swing.JRadioButton radioProovedor;
    private javax.swing.JRadioButton radioStock;
    private javax.swing.JScrollPane scrollPanelTabla;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
